### ISSUE TITLE
Just installed gcmuser-win* not found

### ISSUE THREAD

**Issue by bckelley** [GitCredentialManager/git-credential-manager#1008]
installed using [standalone installation](https://github.com/GitCredentialManager/git-credential-manager/blob/release/docs/install.md#standalone-installation) then you're supposed to run ```gcmuser-win*```  when I do that I get ```ObjectNotFound``` I closed and reopened powershell and still get ```ObjectNotFound```.

Microsoft is such a waste of space.

**Comment by ldennington** [comment]
You should not run `gcmuser-win*`. That part of the instructions is simply informing the user that two different `exe`s are published and to help them determine which is the right one for them to install. All you need to do is run the installer (which it sounds like you've done), and you'll be good to go.

**Comment by bckelley** [comment]
Well then it doesn't work

**Comment by mjcheetham** [comment]
Hi @bckelley!

Are you saying that you're trying to install GCM via the standalone 'user only' installer and the install is failing with the error `ObjectNotFound`.. or have you successfully installed via the standalone installer and are now trying to run a command named `gcmuser-win*` at a PowerShell prompt and receiving the error `ObjectNotFound`?

Once you've installed GCM via the standalone installer it should automatically configure itself as the credential helper with your Git installation. You can check if GCM was installed standalone by looking at the installed apps/programs in Control Panel > Programs and features, or Settings > Apps (depending on your Windows version).

If you are experiencing issues please can you include information that may help us reproduce the problem so that we may investigate, including screenshots of errors, copies of commands run, OS version numbers etc.
