### ISSUE TITLE
Latest release, broken debian install file

### ISSUE THREAD

**Issue by ethanaobrien** [GitCredentialManager/git-credential-manager#1012]
Version [2.0.886](https://github.com/GitCredentialManager/git-credential-manager/releases/tag/v2.0.886) does not install on debian.

I get the following error when running `sudo dpkg -i gcm-linux_amd64.2.0.886.deb`

```
dpkg-deb: error: archive 'gcm-linux_amd64.2.0.886.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive gcm-linux_amd64.2.0.886.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 gcm-linux_amd64.2.0.886.deb
```

However, going back one release to version [2.0.877](https://github.com/GitCredentialManager/git-credential-manager/releases/tag/v2.0.877) the install file works fine, and works fine, although I get the `git-credential-manager-core was renamed to git-credential-manager` error after using after using `git clone` or `git pull` or `git push`, but I can use the software as intended

**Comment by mjcheetham** [comment]
Hello @ethanaobrien!

> dpkg-deb: error: archive 'gcm-linux_amd64.2.0.886.deb' uses unknown compression for member 'control.tar.zst', giving up

This error is due to a bug in our release pipeline that resulted in the 2.0.886 release assets being compressed using a new and less compatible compression algorithm. We've already [merged in a fix](https://github.com/GitCredentialManager/git-credential-manager/pull/1009) for this problem to the `main` branch and should be fixed in the next release.

> [..] although I get the git-credential-manager-core was renamed to git-credential-manager error after using after using git clone or git pull or git push, but I can use the software as intended

This warning message is expected after you have upgraded to at least 2.0.877. You can fix this warning by updating your Git configuration to change the `credential.helper` from `/usr/local/share/gcm-core/git-credential-manager-core` to `/usr/local/share/gcm-core/git-credential-manager`.

**Comment by ethanaobrien** [comment]
Awesome, thank you for your help!
