### ISSUE TITLE
[GCM] "A specified logon session does not exist. It may already have been terminated" while connected through SSH to my workstation

### ISSUE THREAD

**Issue by mikitl** [GitCredentialManager/git-credential-manager#325]
**Which version of GCM Core are you using?**

PS C:\Program Files\Git\mingw64\libexec\git-core> .\git-credential-manager-core.exe --version
2.0.394-beta+3fc6791abf

**Which Git host provider are you trying to connect to?**

* [x] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [ ] GitHub
* [ ] GitHub Enterprise
* [ ] Bitbucket
* [ ] Other - please describe

**Can you access the remote repository directly in the browser using the remote URL?**

* [x] Yes
* [ ] No, I get a permission error
* [ ] No, for a different reason - please describe

---

**_[Azure DevOps only]_ What format is your remote URL?**

* [ ] Not applicable
* [ ] https://dev.azure.com/`{org}`/...
* [x] https://`{org}`@dev.azure.com/`{org}`/...
* [ ] https://`{org}`.visualstudio.com/...

**_[Azure DevOps only]_ If the account picker shows more than one identity as you authenticate, check that you selected the same one that has access on the web.**

* [x] Not applicable
* [ ] I only see one identity
* [ ] I checked each identity and none worked

---

**Expected behavior**

I am authenticated and my Git operation completes successfully.

**Actual behavior**

I'm getting the following error while trying to do any remote git command (pull, push, fetch, etc) `A specified logon session does not exist. It may already have been terminated` while I'm connected to my Remote Windows Workstation through SSH. This error does not happen while doing Remote Desktop and executing the same command there, this only happens in the following scenario:

(( Windows Laptop ))  << ===SSH===>>  (( Remote Windows Workstation ))  <<=====>>  (( Azure DevOps ))

**Logs**

```
(SSH) PS C:\Development\Project> git pull
15:27:42.132411 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
15:27:42.132411 git.c:447               trace: built-in: git pull
15:27:42.148036 run-command.c:667       trace: run_command: git fetch --update-head-ok
15:27:42.186170 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
15:27:42.186170 git.c:447               trace: built-in: git fetch --update-head-ok
15:27:42.186170 run-command.c:667       trace: run_command: GIT_DIR=.git git remote-https origin https://contoso@dev.azure.com/contoso/azure-devops-project/_git/git-repo-name
15:27:42.201794 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
15:27:42.201794 git.c:734               trace: exec: git-remote-https origin https://contoso@dev.azure.com/contoso/azure-devops-project/_git/git-repo-name
15:27:42.201794 run-command.c:667       trace: run_command: git-remote-https origin https://contoso@dev.azure.com/contoso/azure-devops-project/_git/git-repo-name
15:27:42.317392 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
15:27:42.449170 run-command.c:667       trace: run_command: 'git credential-manager-core get'
15:27:42.680450 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
15:27:42.696076 git.c:734               trace: exec: git-credential-manager-core get
15:27:42.696076 run-command.c:667       trace: run_command: git-credential-manager-core get
fatal: Failed to enumerate credentials. [0x520]
fatal: A specified logon session does not exist. It may already have been terminated
15:27:42.965622 run-command.c:667       trace: run_command: bash -c 'cat >/dev/tty && read -r -s line </dev/tty && echo "$line" && echo >/dev/tty'
Password for 'https://contoso@dev.azure.com/contoso/azure-devops-project/_git/git-repo-name':
```

**Comment by mjcheetham** [comment]
Hi @mikitl,

The error you're seeing is related to the way that Windows handles "logon sessions" and "credential sets".

GCM Core uses the Windows Credential Manager (`wincred.h`) to store credentials safely on Windows. We interact with wincred via the Windows APIs: [`CredRead`](https://docs.microsoft.com/en-us/windows/win32/api/wincred/nf-wincred-credreadw), [`CredWrite`](https://docs.microsoft.com/en-us/windows/win32/api/wincred/nf-wincred-credwritew), [`CredDelete`](https://docs.microsoft.com/en-us/windows/win32/api/wincred/nf-wincred-creddeletew), and [`CredEnumerate`](https://docs.microsoft.com/en-us/windows/win32/api/wincred/nf-wincred-credenumeratew).

The error being returned in your case here is `ERROR_NO_SUCH_LOGON_SESSION` (0x520) which means:

> The logon session does not exist or there is no credential set associated with this logon session. **Network logon sessions do not have an associated credential set.**

The key part here is in **bold**.

When you connect via SSH, the `sshd` daemon/Windows service is running as the `NT AUTHORITY\NETWORK SERVICE` account (most likely/by default), which creates network logon sessions when an SSH client connects.

From some searching online, one workaround posted is to change the account that `sshd` runs as to be your real user, which would then have an associated credential set. Your milage may vary here depending on setup.

If you try to use the built-in `cmdkey` command for interacting credentials stores in the Windows Credential Manager, you'll see similar errors or messages like "saved for this login only".

**Comment by oakad** [comment]
VS Code nifty "remote" extension greatly facilitates use of OpenSSH for Windows work. Unfortunately, this issue here is a substantial obstacle, especially when we consider shared windows boxes on the cloud.

One stopgap solution which will be helpful is for wincred to be able:
1. detect the headless operation scenario and avoid hanging up for too long
2. behave sort of like "cache" credential helper in the absence of the full windows session

**Comment by scaryrawr** [comment]
> When you connect via SSH, the `sshd` daemon/Windows service is running as the `NT AUTHORITY\NETWORK SERVICE` account (most likely/by default), which creates network logon sessions when an SSH client connects.
> 
> From some searching online, one workaround posted is to change the account that `sshd` runs as to be your real user, which would then have an associated credential set. Your milage may vary here depending on setup.

I configured sshd to auto start as myself in the service settings and still ran into this issue. It only seems to work if I run it in interactive mode `sshd -d` while logged in as myself over RDP in an elevated prompt.

**Comment by mjcheetham** [comment]
Hello everyone!

With the latest GCM Core release ([v2.0.567](https://github.com/microsoft/Git-Credential-Manager-Core/releases/tag/v2.0.567)) there is support on Windows to use a different credential store other than the Windows Credential Manager that shouldn't have the same remote-session limitations.

You can read more about the different options here: https://aka.ms/gcmcore-credstores

The specific store that may help this SSH scenario is the [DPAPI-protected file store](https://aka.ms/gcmcore-credstores#dpapi-protected-files). Credentials are protected using Windows DPAPI encryption (based on your current user account) and are written to files on disk ([configurable](https://aka.ms/gcmcore-config#credentialdpapistorepath); defaults to `%USERPROFILE%\.gcm\dpapi_store`).

Please give this a try in your SSH scenarios.

**Comment by monil-patel** [comment]
@mjcheetham I stumbled across this thread and appreciate the information about the new credstores options. 
Wanted to see if there was any guidance/planned work around using gcmcore over an SSH connection using keys.

Our Azure Devops org disables using git with ssh keys. So the scenario we are going after is something like this: 

(( Windows Laptop )) < = SSH using keys => (( Remote Windows Workstation )) <=====> (( Azure DevOps cloned using HTTPS ))

From our understanding the DPAPI will only work if the same user also logs in using a method that supplies credentials - such as a RDC session or an SSH session authenticated with username/password. (That will cause DPAPI to start working in the logon session established by the key-authenticated SSH session). That might be a workable compromise, but it eliminates a lot of the usefulness of key-based auth (since username/password credentials still need to be used to complete the scenario).

There's also the question of how you get the access token in the first place. The cached token flow (that requires DPAPI) helps if you already have a cached token to access. But if you don't, most of the authentication methods support by GCM Core won't work in an SSH session (WAM and web view won't work), so GCM Core will fall back to the device code flow,

Thanks!

**Comment by mjcheetham** [comment]
I'm afraid we don't have anything planned right now for using/supporting auth over these SSH tunnel scenarios.

> That might be a workable compromise, but it eliminates a lot of the usefulness of key-based auth (since username/password credentials still need to be used to complete the scenario).

The reasons we've seen for Azure DevOps org admins to disable SSH is because they consider SSH "not secure" or rather "not secure enough". What this typically boils down to is there is no ability to continuously evaluate Conditional Access Policies. AAD access tokens provide CAP evaluation that many orgs now require (think Intune/AAD join, requiring up-to-date OS, firewall rules, etc).

Avoiding non-key based access here is probably not possible, unless there's a more joined up story with brokers, AAD, and SSH.

Technologies like WAM don't work remotely as is currently exposed to us; the user must be physically present at the device that has the credentials stored/account connected.

> There's also the question of how you get the access token in the first place.
> [..] most of the authentication methods support by GCM Core won't work in an SSH session (WAM and web view won't work), so GCM Core will fall back to the device code flow,

This is another unfortunate problem. Also to have some CA policies enforced means you typically cannot use the device code flow since the authentication is performed on the "other" device, and no attestation is performed on the "origin" device.

cc @bgavrilMS

**Comment by bgavrilMS** [comment]
Agreed with all of the above. That said, while DPAPI might not be available over SSH, WAM might be available. WAM should work even if MSAL is not able to persist a token cache (it'll be slower though).

**Comment by mjcheetham** [comment]
Closing this issue. GCM now has support for DPAPI file-based credential store, which works around the limitations of network logon sessions on Windows.

Regarding limitations with WAM on headless, there's not much GCM can do here. The spirit of WAM and brokers in general is to secure the machine that's making the auth requests, so naturally this is ill-defined in remote scenarios. Some form of interactive auth will always be required in these situations with WAM unless Windows can come up with some solution.
