### ISSUE TITLE
Doesn't work with WSL when Git for Windows is not installed

### ISSUE THREAD

**Issue by bavis-m** [GitCredentialManager/git-credential-manager#376]
I use native linux git on WSL without having Git for Windows installed. I installed GCMC and set it to be my credential manager in git, but it fails with: `Failed to locate 'git.exe' executable on the path`. I'd prefer not to have to install Git for Windows if I can, but as far as I can see from the code, there is no support for using git from within WSL (even if I installed Git for Windows, it would grab git settings from my un-configured GfW install).

**Comment by vtbassmatt** [comment]
This should be fixed with #461 (which isn't yet released but is coming soon).

**Comment by mjcheetham** [comment]
Hi @pranavAbe,

From your screenshot it looks like you've got the environment variables a little wrong.

In **_Windows_** you want to set the following:

Variable|Value
-|-
`WSLENV`|`GIT_EXEC_PATH/wp`
`GIT_EXEC_PATH`|_(should not be set; Git inside of WSL will set this at runtime)_

The Git configuration _inside of **WSL** looks correct_, it should be:

```ini
[credential]
    helper = /mnt/c/Program\\ Files\\ \\(x86\\)/Git\\ Credential\\ Manager\\ Core/git-credential-manager-core.exe
```

> Additionally, the command `git credential-manager-core --version` is not recognized by the Git on WSL, which makes me wonder if Git on WSL is even able to recognize my GCM Core on Windows still.

Any command of the form `git <foo>` will make Git search for either a built-in command, for an executable in the `GIT_EXEC_PATH` with the name `git-foo`. Since GCM is not installed inside of WSL, the WSL Git will not find GCM using this command. **This is expected.**

This is the reason the `credential.helper` setting in the WSL Git config must be the full file path to GCM, starting with `/mnt/c/...`.

**Comment by pranavAbe** [comment]
Hey @mjcheetham, thanks for getting back to me!

I've corrected the `WSLENV` variable as you pointed out above, and removed the `GIT_EXEC_PATH` to allow WSL Git to configure that itself. 
<img width="353" alt="image" src="https://user-images.githubusercontent.com/29583966/140389533-093d8972-2bfc-421c-9ec8-aaa65d8fea04.png">

My `.gitconfig` is unchanged from the screenshot sent earlier, as you've stated that it's configured correctly. 

And yet I seem to run upon this error while trying to use Git. 
![image](https://user-images.githubusercontent.com/29583966/140389680-9fd967d0-2db2-43b6-958d-afd9a7e3993b.png)

Any further suggestions on what might be wrong here? 🙁

**Comment by phillipov** [comment]
One of the problems is that installing GCM Core on Windows (in my case, the `gcmcoreuser-win-x86` installer) does not create the `C:\Program Files\Git` or `C:\Program Files (x86)\Git` directories. I don't even know where `git-credential-manager-core.exe` was installed, so I cannot configure `credential.helper` in WSL's Git because I don't know the correct path. I tried searching my user directory for `git-credential-manager-core.exe` and I couldn't find it.

If the GCM Core maintainers can answer this, then the problem can be solved:

When a user does not have Git for Windows installed, but installs the latest release of `gcmcoreuser-win-x86-VERSION.exe` to get standalone GCM Core, where is `git-credential-manager-core.exe` installed?

**Comment by pranavAbe** [comment]
@phillipov I believe the Git Credential Manager Core on Windows is installed at `C:/Program Files (x86)/Git Credential Manager Core` by default. And you're right, Git Credential Manager Core will not create `C:\Program Files\Git` or `C:\Program Files (x86)\Git` directories, since those are created when you install **Git on Windows**. 

You can also edit the configuration and add the `credential.helper` for **Git on WSL**, by editing the `.gitconfig` file located at `~/.gitconfig`. To do this automatically using the terminal, you can just type in `git config --global credential.helper /mnt/c/Program\ Files\ \(x86\)/Git\ Credential\ Manager\ Core/git-credential-manager-core.exe` into the terminal.

**Comment by phillipov** [comment]
@pranavAbe Thanks - I figured it out! It wasn't in `C:\Program Files (x86)\Git Credential Manager Core` because I didn't use the `gcmcore-win-x86` installer. It was actually in `%LocalAppData%\Programs\Git Credential Manager Core` because I used the `gcmcoreuser-win-x86` installer.

**Solution for WSL if you installed `gcmcoreuser-win-x86`:**
Open your WSL terminal and run:
```
git config --global credential.helper "$(wslpath "$(cmd.exe /c echo %LocalAppData%\\Programs\\Git Credential Manager Core\\git-credential-manager-core.exe)")"
```

**Comment by phillipov** [comment]
My previous solution is **wrong!** I did not test it thoroughly.

**Correct solution for WSL if you installed `gcmcoreuser-win-x86`**
---
Open your WSL terminal and run:
```bash
git config --global credential.helper "$(wslpath "$(cmd.exe /c echo %LocalAppData%\\Programs\\Git Credential Manager Core\\git-credential-manager-core.exe 2>/dev/null)" | sed -e 's/\r//g' -e 's/ /\\ /g')"
echo >> ~/.bashrc
echo 'export GIT_EXEC_PATH="$(git --exec-path)"' >> ~/.bashrc
echo 'export WSLENV=$WSLENV:GIT_EXEC_PATH/wp' >> ~/.bashrc
source ~/.bashrc
```
To test this, try inspecting one of your private GitHub repositories (using HTTPS) in a WSL2 terminal.
```
git ls-remote https://github.com/YOUR-USERNAME/YOUR-PRIVATE-REPO.git
```
After I get more sleep and motivation, I will explain each command. It's a bit convoluted, I know.

**Comment by phillipov** [comment]
## `git config` commands explained
```bash
git config --global credential.helper "$(wslpath "$(cmd.exe /c echo %LocalAppData%\\Programs\\Git Credential Manager Core\\git-credential-manager-core.exe 2>/dev/null)" | sed -e 's/\r//g' -e 's/ /\\ /g')"
```
I'll approach this from the bottom-up. To start, the GCM Core standalone executable (user installation, not system-wide installation) is at the Windows path `%LocalAppData%\\Programs\\Git Credential Manager Core\\git-credential-manager-core.exe`. The environment variable `%LocalAppData%` points to `C:\Users\your_username\AppData\Local`.

How can WSL read the Windows environment variable `%LocalAppData%`? WSL can read the Windows `%PATH%`, so we can call `cmd.exe` from WSL.
```bash
cmd.exe /c echo %LocalAppData%\\Programs\\Git Credential Manager Core\\git-credential-manager-core.exe
```

This returns `C:\Users\your_username\AppData\Local\Programs\Git Credential Manager Core\git-credential-manager-core.exe`. However, it also complains that "UNC paths are not supported". To silence that error spam, we pipe the standard error (stderr) stream from `cmd.exe` to `/dev/null`, a Linux "device" that discards everything written to it. This will give us just the path, not the error spam:
```bash
cmd.exe /c echo %LocalAppData%\\Programs\\Git Credential Manager Core\\git-credential-manager-core.exe 2>/dev/null
```
The double-backslashes `\\` are to prevent the WSL bash shell from reading a single backslash `\` as an escape character. `cmd.exe` will only see single backslashes.

Okay, so now we have a Windows path to `git-credential-manager-core.exe`. We need to translate this into a WSL path for Git. We'll use `wslpath`:
```
wslpath "$(cmd.exe /c echo %LocalAppData%\\Programs\\Git Credential Manager Core\\git-credential-manager-core.exe 2>/dev/null)"
```
Now that returns a WSL path! However, `git config` can't understand it yet. First of all, it ends with an invisible carriage return character `\r` because of `cmd.exe`, so we need to remove that. We also need to escape all the spaces we send to `git config` with a backslash `\ ` so the spaces in the path are parsed correctly.

`sed` (stream editor) to the rescue!
```bash
# Replace all carriage returns with nothing.
sed 's/\r//g'
# Replace all spaces with a backlash and a space.
sed 's/ /\\ /g'
# Combine those two statements into one sed command.
sed -e 's/\r//g' -e 's/ /\\ /g'
```
Piping from `wslpath` to `sed`:
```bash
wslpath "$(cmd.exe /c echo %LocalAppData%\\Programs\\Git Credential Manager Core\\git-credential-manager-core.exe 2>/dev/null)" | sed -e 's/\r//g' -e 's/ /\\ /g'
```
This gives us `/mnt/c/Users/your_windows_username/AppData/Local/Programs/Git\ Credential\ Manager\ Core/git-credential-manager-core.exe`. Hooray!

We can finally use this command in `git config` to set the path to the credential helper (GCM Core in Windows):
```bash
git config --global credential.helper "$(wslpath "$(cmd.exe /c echo %LocalAppData%\\Programs\\Git Credential Manager Core\\git-credential-manager-core.exe 2>/dev/null)" | sed -e 's/\r//g' -e 's/ /\\ /g')"
```

## `.bashrc` commands explained
`~/.bashrc` is a file that runs arbitrary commands to set up your Linux bash shell before you run it. You can use this to set environment variables and other stuff for WSL.
```bash
echo >> ~/.bashrc
echo 'export GIT_EXEC_PATH="$(git --exec-path)"' >> ~/.bashrc
echo 'export WSLENV=$WSLENV:GIT_EXEC_PATH/wp' >> ~/.bashrc
source ~/.bashrc
```

Again, I'll explain this from the bottom-up.

`GIT_EXEC_PATH` tells programs where to find all the Git executables. Since GCM Core can't find Git for Windows, we can tell it to follow the WSL Git path. Git can tell us where its executables are with `git --exec-path`.
```bash
export GIT_EXEC_PATH="$(git --exec-path)"
```
But this is a path in WSL. How would GCM Core find this WSL environment variable from Windows, and how would it translate it into a Windows path? [`WSLENV`](https://devblogs.microsoft.com/commandline/share-environment-vars-between-wsl-and-windows/) to the rescue!

`WSLENV` is an environment variable that contains a colon-separated list of other environment variables to be shared and translated between Windows and WSL. You can set it on either the Windows or WSL side.
```bash
export WSLENV=$WSLENV:GIT_EXEC_PATH/wp
```
We don't want to overwrite anything already in `WSLENV`, so we begin it with `$WSLENV:` to append to the existing `WSLENV` value.

Then we add `GIT_EXEC_PATH` to the list with some flags. `/w` means "this is only visible to Windows when we call a Windows command from WSL". In other words, GCM Core in Windows can see `GIT_EXEC_PATH` because we called GCM Core from WSL using Git, but a process that started in Windows alone cannot see it. `/p` means "translate paths between WSL and Windows". Combined, we have `/wp`.

Now we add this to `.bashrc`:
```bash
# Send a newline to not write on the same line as the last .bashrc command.
echo >> ~/.bashrc
# Set the GIT_EXEC_PATH environment variable.
echo 'export GIT_EXEC_PATH="$(git --exec-path)"' >> ~/.bashrc
# Set the WSLENV shared environment variable.
echo 'export WSLENV=$WSLENV:GIT_EXEC_PATH/wp' >> ~/.bashrc
# Re-evaluate .bashrc so we don't have to restart our terminal to use the new variables.
source ~/.bashrc
```

I hope you learned something new 🗿

**Comment by mjcheetham** [comment]
Hello 👋 

> I don't even know where git-credential-manager-core.exe was installed, so I cannot configure credential.helper in WSL's Git because I don't know the correct path. I tried searching my user directory for git-credential-manager-core.exe and I couldn't find it.
>
> If the GCM Core maintainers can answer this, then the problem can be solved:

The user-installer for GCM installs to `%LocalAppData%\Programs` rather than %ProgramFiles(x86)%, as others have discovered.

I have updated the [WSL documentation/instructions](https://aka.ms/gcm/wsl#using-the-user-only-gcm-installer) to include a section on the location of the user-only GCM installer.

**Comment by nash8114** [comment]
@phillipov Thanks for posting the solution. The documentation appears to mention that the WSLENV variable should be set in Windows, but that doesn't work. Probably because the variable gets transferred from the WSL environment when invoking `git` from WSL. Setting WSLENV in windows is only useful if you want to use the credential manager from windows. But why would you, if you don't have git installed there?
After setting my WSLENV environment variable in .zprofile, it worked fine. There is no need to export GIT_EXEC_PATH, as git does that automagically.
```
# Add GIT_EXEC_PATH to WSLENV, but only if not already present
if ! [[ "$WSLENV" =~ (^|:)GIT_EXEC_PATH/wp($|:) ]]; then
  export WSLENV="${WSLENV+$WSLENV:}GIT_EXEC_PATH/wp"
fi
```

**Comment by daramir** [comment]
> Setting WSLENV in windows is only useful if you want to use the credential manager from windows. But why would you, if you don't have git installed there?

Even with Git installed on Windows this issue came up 🥲 . 
I followed your solution and it worked  @nash8114 , thanks.

**Comment by chipbite** [comment]
> From your screenshot it looks like you've got the environment variables a little wrong.
> 
> The Git configuration _inside of **WSL** looks correct_, it should be:
> 
> [credential]
>     helper = /mnt/c/Program\\ Files\\ \\(x86\\)/Git\\ Credential\\ Manager\\ Core/git-credential-manager-core.exe

WOW! This was it. I was almost giving up hope. 
This helped me fix my issue. Now everything works again.
Thanks.
