### ISSUE TITLE
Port to alpine linux?

### ISSUE THREAD

**Issue by gabyx** [GitCredentialManager/git-credential-manager#380]
Could we have a release which features alpine and possible other linux?

**Comment by vtbassmatt** [comment]
Our supported distros are Debian-based and Fedora-based, with best-effort support for all others.

Since Alpine is `musl`-based, we'd have to target `linux-musl-x64` when publishing. This is something we could consider adding to the project files (even though we still won't ship packages). @mjcheetham @vdye what do you think?

**Comment by mjcheetham** [comment]
As of https://github.com/GitCredentialManager/git-credential-manager/pull/630 we now support building/installing GCM on Linux from source via an easy to consume script! This should make it easier to get GCM on Alpine up and running. Please let us know by opening a new issue if you encounter problems! 😁
