### ISSUE TITLE
Ubuntu 20.04 Support

### ISSUE THREAD

**Issue by hoangtnm** [GitCredentialManager/git-credential-manager#422]
Hi, when reading [installation guide](https://github.com/microsoft/Git-Credential-Manager-Core#linux) for Ubuntu, it seems that ubuntu 20.04 is missing, so how can I install it for Ubuntu 20.04? thank you

**Comment by ldennington** [comment]
You can follow the instructions for **Other Ubuntu/Debian Distributions** in the `[README](https://github.com/microsoft/Git-Credential-Manager-Core#linux)`. Pasting the instructions here for convenience:

Download the latest [.deb](https://github.com/microsoft/Git-Credential-Manager-Core/releases/latest) package, and run the following:

```
sudo dpkg -i <path-to-package>
git-credential-manager-core configure
```

**Comment by felipecrs** [comment]
Or also

```
sudo apt install ./gcmcore.deb
```

But still, will the updates through apt work when installing directly from the `deb`?

**Comment by felipecrs** [comment]
Another point which is important to mention is that it's much harder for scripts to install `gcmcore` having to download the `.deb` file.

**Comment by ldennington** [comment]
I don't think `apt` updates will work when you install from the `.deb` file, but I will test today to verify and circle back.

**Comment by ldennington** [comment]
I stand corrected. I experimented with the following today on a 20.04 machine and it worked...

## Part 1: Manually install outdated package
Downloaded an old `.deb` package ([`2.0.452`](https://github.com/microsoft/Git-Credential-Manager-Core/releases/download/v2.0.452/gcmcore-linux_amd64.2.0.452.3248.deb))
```
sudo dpkg -i gcmcore-linux_amd64.2.0.452.3248.deb
git-credential-manager-core configure
```

## Part 2: Upgrade using `apt-get`
```
curl -sSL https://packages.microsoft.com/config/ubuntu/21.04/prod.list | sudo tee /etc/apt/sources.list.d/microsoft-prod.list
curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc
sudo apt-get update
sudo apt-get upgrade gcmcore
```
The only thing that's wonky here is that, since we're not publishing to a dedicated 20.04 feed, I had to add the 21.04 feed. This feels like I may have been wrong in thinking we should deploy to different repos for different ubuntu versions. Perhaps we should return to the original architecture in which we just deployed to the [`git` feed](https://packages.microsoft.com/repos/git/pool/main/g/). @mjcheetham, thoughts?

**Comment by mjcheetham** [comment]
> Perhaps we should return to the original architecture in which we just deployed to the [`git` feed](https://packages.microsoft.com/repos/git/pool/main/g/). @mjcheetham, thoughts?

We don't have any real differences in dependencies between the different distributions, so perhaps the singular `git` feed would be better?

Our main dependencies are `libsecret` and dependencies of the .NET runtime itself. We publish GCM against the generic `linux-x64` target framework which brings along most (all?) dependencies for the runtime. For `libsecret` we only depend on it if you opt to use [the `secretservice` credential store](https://aka.ms/gcmcore-linuxcredstores#1-freedesktoporg-secret-service-api), and even then [we work with old versions of `libsecret`](https://github.com/microsoft/Git-Credential-Manager-Core/pull/244).

**Comment by mjcheetham** [comment]
Closing this issue as Ubuntu 20.04 is supported/works by installing the Debian package downloaded from the releases page.

For tracking apt-get feed support we can use #447
