### ISSUE TITLE
Unable to force non-GUI mode on macOS

### ISSUE THREAD

**Issue by mislav** [GitCredentialManager/git-credential-manager#637]
I'm testing out various git-credential-manager features and I wanted to check how its interactivity works in terminal on macOS. However, git-credential-manager always seems to open its GUI, even if I'm trying to explicitly disable it for the purpose of testing.

```
% git credential-manager-core --version
2.0.632+478753bbb7
```
```gitconfig
# ~/.gitconfig
[credential]
	helper = 
	helper = /usr/local/share/gcm-core/git-credential-manager-core
	guiPrompt = false
[credential "https://dev.azure.com"]
	useHttpPath = true
```

I've cleared out my previously cached credentials from Keychain. Then, when I run:
```
GCM_GUI_PROMPT=0 git pull
```
I expect to see some GCM interactive prompts in the terminal; however, it opens up its GUI nevertheless.

<img width="532" alt="" src="https://user-images.githubusercontent.com/887/159680999-d95d10cd-0717-452b-8381-0576159a9a63.png">

**Comment by buchwasa** [comment]
Looks like this issue has been fixed for a while on the main branch

**Comment by ldennington** [comment]
Yes, I believe this functionality was added [here](https://github.com/GitCredentialManager/git-credential-manager/commit/1483f3efce41d817eb5e6997c8bbffdffc0191a8). However, since we haven't released since December, it's not yet in the wild. I'm planning to work with @mjcheetham to get a release out this week, though, ahead of the upcoming Git for Windows release cycle.

**Comment by mislav** [comment]
Ahh I made the classic mistake of reading the README for the main branch, forgetting that this might document unreleased features. Thanks @buchwasa @ldennington
