### ISSUE TITLE
WAM support silent authentication? 

### ISSUE THREAD

**Issue by monil-patel** [GitCredentialManager/git-credential-manager#687]
**Which version of GCM are you using?**

From a terminal, run `git credential-manager-core --version` and paste the output.

2.0.632+478753bbb7 (Windows 11)

**Which Git host provider are you trying to connect to?**

* [x] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [ ] GitHub
* [ ] GitHub Enterprise
* [ ] Bitbucket
* [ ] Other - please describe

**Can you access the remote repository directly in the browser using the remote URL?**

From a terminal, run `git remote -v` to see your remote URL.

* [x] Yes
* [ ] No, I get a permission error
* [ ] No, for a different reason - please describe

---

**_[Azure DevOps only]_ What format is your remote URL?**

* [ ] Not applicable
* [x] https://dev.azure.com/`{org}`/...
* [ ] https://`{org}`@dev.azure.com/`{org}`/...
* [x] https://`{org}`.visualstudio.com/...

**_[Azure DevOps only]_ If the account picker shows more than one identity as you authenticate, check that you selected the same one that has access on the web.**

* [ ] Not applicable
* [x] I only see one identity
* [ ] I checked each identity and none worked

---

We are trying out the new experimental feature for WAM support

I ran `git config --global credential.msauthUseBroker true`

**Expected behavior**
Since I used windows hello to sign in I expect to have silent login 

**Actual behavior**
I get a prompt to select my account 

**Thoughts** 
Support either IWA or WAM silent (for WAM silent, see the documentation [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-desktop-acquire-token-wam), the key is to use OperatingSystemAccount)

Probably put this behind a GCM option, maybe default to off, we can enable it for our scenario.
Any plans to support silent login on windows?

**Comment by mjcheetham** [comment]
@monil-patel thanks for raising this. The biggest problem today in implementing a silent auth that uses the OS account is handling the cases where the OS account _isn't_ the account the user wants to use for that particular Azure DevOps org.

Git gives us one chance to "get the correct credentials" for the particular host, otherwise it fails and writes out "fatal: Authentication failed.".

When we get the request from Git for credentials we discover the AAD tenant ID (or discover this is MSA-backed) and _could_ use this to more intelligently select an existing account (current OS account or otherwise) that exists in that tenant. However the problem is how to handle the failure mode for those users that have multiple accounts in the same tenant and we've selected the "wrong" account.

We've seen this in the past with old/retired GCM for Windows which supported IWA - users who, for example, needed to run an IDE like Visual Studio (that call Git and GCM) as one user account to get access to a database, but that same user didn't have source code access.

Git does call GCM back with the `erase` command when credentials do not work, but 1) this is made as a separate process invocation meaning we cannot associate the failure to the `get` request that came before it, and 2) we are not given a chance to ask Git to retry with a different credential or user account.

For what it's worth, you can workaround these problems and achieve a silent auth after the first prompt where we ask you to select the correct user account to use.

> Probably put this behind a GCM option, maybe default to off, we can enable it for our scenario.

You can pre-emptively select the correct account by telling us explicitly via Git config:

```shell
> git credential-manager-core azure-repos bind --help
bind
  Bind a user account to an Azure DevOps organization

Usage:
  git-credential-manager-core [options] azure-repos bind [<organization> <username>]

Arguments:
  <organization>  Azure DevOps organization name
  <username>      Username or email (e.g.: alice@example.com)

Options:
  --local         Target the local repository Git configuration
  -?, -h, --help  Show help and usage information
```

..for example:

```shell
git credential-manager-core azure-repos bind contoso alice@contoso.com
```

> Any plans to support silent login on windows?

This is something we're hopeful we can improve over time with enhancements to Git's interaction with credential helpers, and better account selection heuristics in GCM.

**Comment by monil-patel** [comment]
@mjcheetham really appreciate the detailed response, definitely helps our team understand the reasoning. 

Will take a look at that bind approach
