### ISSUE TITLE
Cannot leverage GIT Credential Manager from VS Code

### ISSUE THREAD

**Issue by MonkeyTennis** [GitCredentialManager/git-credential-manager#755]
**Which version of GCM are you using?**

Git-2.36.1-64-bit

From a terminal, run `git credential-manager-core --version` and paste the output.

2.0.696+4365b917da

**Which Git host provider are you trying to connect to?**

Azure DevOps

**Can you access the remote repository directly in the browser using the remote URL?**

yes

From a terminal, run `git remote -v` to see your remote URL.

origin  https://<redacted> (fetch)
origin  https://<redacted> (push) 

Yes

---

**_[Azure DevOps only]_ What format is your remote URL?**

* [x ] https://`{org}`@dev.azure.com/`{org}`/...

**_[Azure DevOps only]_ If the account picker shows more than one identity as you authenticate, check that you selected the same one that has access on the web.**

* [ x] I only see one identity

---

**Expected behavior**

I am authenticated and my Git operation completes successfully.

**Actual behavior**

I attempt to perform a GIT operation on an already cloned repo (achieved via Visual Studio) using VS Code and get an error dialog:

![image](https://user-images.githubusercontent.com/1092060/174786111-1a5b65af-976d-4771-9245-e5d0105f71e0.png)

**Logs**

IMPORTANT - Authentication works fine via Visual Studio 2022, which is how I cloned the repo in the first place. However, attempting to perform GIT operations on the cloned repo via VS Code fails as below.

IMPORTANT - This used to work fine from VS Code and now doesn't.

[2022-06-21T11:13:28.475Z] Log level: Info
[2022-06-21T11:13:28.476Z] [info] Validating found git in: C:\Program Files\Git\cmd\git.exe
[2022-06-21T11:13:28.824Z] [info] Using git 2.36.1.windows.1 from C:\Program Files\Git\cmd\git.exe
[2022-06-21T11:13:28.953Z] > git rev-parse --show-toplevel [118ms]
[2022-06-21T11:13:29.402Z] > git rev-parse --git-dir --git-common-dir [441ms]
[2022-06-21T11:13:29.404Z] [info] Open repository: c:\Users\bcotier\source\repos\SIS
[2022-06-21T11:13:29.672Z] > git status -z -uall [261ms]
[2022-06-21T11:13:29.763Z] > git symbolic-ref --short HEAD [85ms]
[2022-06-21T11:13:29.838Z] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/main refs/remotes/main [70ms]
[2022-06-21T11:13:29.929Z] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [86ms]
[2022-06-21T11:13:29.932Z] > git remote --verbose [83ms]
[2022-06-21T11:13:30.038Z] > git config --get commit.template [98ms]
[2022-06-21T11:13:30.044Z] > git check-ignore -v -z --stdin [97ms]
[2022-06-21T11:13:44.199Z] > git fetch [1535ms]
[2022-06-21T11:13:44.199Z] git: 'credential-manager' is not a git command. See 'git --help'.

The most similar command is
	credential-manager-core
Missing or invalid credentials.
Wrong number of arguments
git: 'credential-manager' is not a git command. See 'git --help'.

The most similar command is
	credential-manager-core
fatal: Authentication failed for '<redacted>'

**Comment by mjcheetham** [comment]
> [2022-06-21T11:13:44.199Z] git: 'credential-manager' is not a git command. See 'git --help'.

This looks like there's some problem with Git configuration `credential.helper`.
Can you please try running the following and reporting back the results?

```shell
git config --get-all --show-origin credential.helper
```

**Comment by MonkeyTennis** [comment]
file:C:/Program Files/Git/etc/gitconfig manager-core
file:C:/Users/bcotier/.gitconfig        
file:C:/Users/bcotier/.gitconfig        manager

**Comment by MonkeyTennis** [comment]
@ldennington That ran without error and I am now able to authenticate to ADO. Thanks for your help.

I now have the cure but can you explain what the cause was? I'm not aware of having done anything unusual.

Thanks again.

**Comment by mjcheetham** [comment]
> That ran without error and I am now able to authenticate to ADO.

Great to hear! 🎉 

> I now have the cure but can you explain what the cause was? I'm not aware of having done anything unusual.

The output from the `git config --get-all --show-origin credential.helper` command was:

```text
file:C:/Program Files/Git/etc/gitconfig manager-core
file:C:/Users/bcotier/.gitconfig
file:C:/Users/bcotier/.gitconfig manager
```

This means at some point, in your user Git configuration (`C:\Users\bcotier\.gitconfig`), something/one (likely a tool or script) set both the empty string and the `manager` values.

The effect of the empty is to prevent Git from attempting to use any previously listed credential helpers – in this case to prevent Git from using `manager-core` (`git-credential-manager-core`).

In [Git for Windows 2.33.1](https://github.com/git-for-windows/git/releases/tag/v2.33.1.windows.1), the legacy/not-in-development "Git Credential Manager for Windows" was removed, leaving only the new Git Credential Manager (previously named GCM Core).

This older version of GCM had the executable name `git-credential-manager`, and the Git config name of `manager`. Since this executable has been removed from the Git for Windows installation, but your Git config was telling Git it was only allowed to search for `manager` and not `manager-core`, you got the error:

> git: 'credential-manager' is not a git command. See 'git --help'.

By removing both the empty string and `manager` lines from your user Git configuration, the only helper left for Git to use it `manager-core`, which does exist.
